<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MCeToJava" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Solace.Common\Solace.Common.csproj" />
    <ProjectReference Include="..\Solace.DB\Solace.DB.csproj" />
    <ProjectReference Include="..\Solace.EventBus.Client\Solace.EventBus.Client.csproj" />
    <ProjectReference Include="..\Solace.ObjectStore.Client\Solace.ObjectStore.Client.csproj" />
  </ItemGroup>

</Project>
